---

- name: Update packages
  become: yes
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes

- name: Upgrade packages
  become: yes
  ansible.builtin.apt:
    force_apt_get: yes
    upgrade: dist

- name: Disable DNS check on SSH
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'UseDNS no'
    regexp: '^\s*#?\s*UseDNS'

- name: Enable TCP keep-alive on SSH
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'TCPKeepAlive yes'
    regexp: '^\s*#?\s*TCPKeepAlive'

- name: Restart SSH service
  become: yes
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Set timezone to {{ timezone }}
  become: yes
  community.general.timezone:
    name: "{{ timezone }}"

- name: Add hardware peripheral support
  become: yes
  ansible.builtin.lineinfile:
    create: yes
    dest: /boot/firmware/usercfg.txt
    line: "{{ item }}"
  loop:
    - dtparam=i2c_vc=on
    - dtoverlay=dwc2,dr_mode=host
    - dtoverlay=i2c-rtc,pcf85063a,i2c_csi_dsi
