network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 172.31.255.1/24
      gateway4: 172.31.255.254
      nameservers:
        addresses: [172.31.255.254]
