---

- name: Deny all incomming
  become: yes
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow all outgoing
  become: yes
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow 22/tcp (SSH)
  become: yes
  community.general.ufw:
    # interface: ember # TODO: Enable after debug
    rule: allow
    port: 22
    proto: tcp

- name: Allow 1700/udp (LoRaWAN)
  become: yes
  community.general.ufw:
    # interface_in: ember
    rule: allow
    port: 1700
    proto: udp

- name: Allow 8080/tcp (ChirpStack)
  become: yes
  community.general.ufw:
    # interface_in: ember
    rule: allow
    port: 8080
    proto: tcp

- name: Allow 1880/tcp (Node-RED)
  become: yes
  community.general.ufw:
    # interface_in: ember
    rule: allow
    port: 1880
    proto: tcp

#- name: Allow 51820/udp (WireGuard)
#  become: yes
#  community.general.ufw:
#    rule: allow
#    port: 51820
#    proto: udp

- name: Allow anywhere from localhost
  become: yes
  community.general.ufw:
    rule: allow
    src: 127.0.0.1

- name: Enable UFW
  become: yes
  community.general.ufw:
    state: enabled
