---

- name: Deny all incomming
  become: yes
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow all outgoing
  become: yes
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow 22/tcp (SSH)
  become: yes
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow 1700/udp (LoRaWAN)
  become: yes
  community.general.ufw:
    rule: allow
    port: 1700
    proto: udp

- name: Allow 8080/tcp (ChirpStack)
  become: yes
  community.general.ufw:
    rule: allow
    port: 8080
    proto: tcp

- name: Allow 1880/tcp (Node-RED)
  become: yes
  community.general.ufw:
    rule: allow
    port: 1880
    proto: tcp

- name: Enable UFW
  become: yes
  community.general.ufw:
    state: enabled

- name: Copy netplan configuration file
  become: yes
  ansible.builtin.copy:
    src: config.yaml
    dest: /etc/netplan/

- name: Remove previous netplan configurations
  become: yes
  ansible.builtin.file:
    path: /etc/netplan/*.yaml
    state: absent

- name: Apply netplan configuration
  become: yes
  ignore_errors: true
  command: netplan apply
  async: 10
  poll: 5
