---

- name: Add Node.js APT key
  become: yes
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add Node.js 14 to APT
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main
    update_cache: yes

- name: Install Node.js
  become: yes
  ansible.builtin.apt:
    name: nodejs
